# Generated by Django 3.0.6 on 2020-05-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Upload Date'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.TextField(verbose_name='Movie Description'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.CharField(max_length=50, verbose_name='Movie Image'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Movie Title'),
        ),
    ]
